# Site settings
title: SarahhhC Creative Factory
email: joytutu29@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://SarahhhC.github.io/" # the base hostname & protocol for your site

# Sidebar settings
description: Software Engineer,       Love to Create

# Social icons
facebook: facebook.com/sarahcho11
linkedin: sarah-cho-61b645ab
github: SarahhhC
#deviantart: username

google_analytics_id: 'UA-104123155-1'

footer: ©SarahCho

# Build settings
markdown: kramdown
