# Site settings
title: SarahhhC
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://SarahhhC.github.io/" # the base hostname & protocol for your site

# Sidebar settings
description: developer, Seoul

# Social icons
facebook: sarahcho11
linkedin: username
github: SarahhhC
#deviantart: username
#codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
